### ISSUE TITLE
Coverage path issues

### ISSUE THREAD

**Issue by tsauvajon** [eddyerburgh/vue-jest#21]
I've got path issues when generating the Jest coverage report: `yarn jest --coverage` when switching from Karma to Jest. My lcov report with Karma worked perfectly (i.e. relative paths rather than absolute paths, and no "unknown" entry).

I followed the steps from the [vue-test-utils](https://vue-test-utils.vuejs.org/en/guides/testing-SFCs-with-jest.html) doc

``` console
--------------------------------------------------------------------------------|----------|----------|----------|----------|----------------|
All files                                                                       |      100 |      100 |      100 |      100 |                |
 root                                                                           |      100 |      100 |      100 |      100 |                |
  unknown                                                                       |      100 |      100 |      100 |      100 |                |
 root/GOPATH/src/bitbucket.org/username/app/client/src/app      |      100 |      100 |      100 |      100 |                |
  api.js                                                                        |      100 |      100 |      100 |      100 |                |
 root/GOPATH/src/bitbucket.org/username/app/client/src/auth     |      100 |      100 |      100 |      100 |                |
  actions.js                                                                    |      100 |      100 |      100 |      100 |                |
  mutations.js                                                                  |      100 |      100 |      100 |      100 |                |
  store.js                                                                      |      100 |      100 |      100 |      100 |                |
 root/GOPATH/src/bitbucket.org/username/app/client/src/projects |      100 |      100 |      100 |      100 |                |
  mocks.js                                                                      |      100 |      100 |      100 |      100 |                |
--------------------------------------------------------------------------------|----------|----------|----------|----------|----------------|
```

The `unknown` file has the following content on the lcov report:
``` console
Path must be a string. Received [Function]
TypeError: Path must be a string. Received [Function]
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:221:7)
    at Object.exports.asAbsolute (C:\GOPATH\src\bitbucket.org\[username]\[app]\client\node_modules\istanbul-lib-source-maps\lib\pathutils.js:12:43)
    at Context.sourceFinder (C:\GOPATH\src\bitbucket.org\[username]\[app]\client\node_modules\istanbul-lib-source-maps\lib\map-store.js:97:42)
    at Context.getSource (C:\GOPATH\src\bitbucket.org\[username]\[app]\client\node_modules\istanbul-lib-report\lib\context.js:74:17)
    at Object.annotateSourceCode (C:\GOPATH\src\bitbucket.org\[username]\[app]\client\node_modules\istanbul-reports\lib\html\annotator.js:172:38)
    at HtmlReport.onDetail (C:\GOPATH\src\bitbucket.org\[username]\[app]\client\node_modules\istanbul-reports\lib\html\index.js:217:39)
    at LcovReport.(anonymous function) [as onDetail] (C:\GOPATH\src\bitbucket.org\[username]\[app]\client\node_modules\istanbul-reports\lib\lcov\index.js:24:24)
    at Visitor.(anonymous function) [as onDetail] (C:\GOPATH\src\bitbucket.org\[username]\[app]\client\node_modules\istanbul-lib-report\lib\tree.js:34:30)
    at ReportNode.Node.visit (C:\GOPATH\src\bitbucket.org\[username]\[app]\client\node_modules\istanbul-lib-report\lib\tree.js:123:17)
```

Here's my `package.json` jest config:
``` json
"jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "vue"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
      ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest"
    },
    "mapCoverage": true,
    "moduleNameMapper": {
      "^@/(.*)$": "<rootDir>/src/$1"
    },
}
```

I tested it on Linux and Windows, and have the same results.

My application is generated with the `webpack` template from `vue-cli`.

https://github.com/eddyerburgh/vue-test-utils-jest-example works well and doesn't display the full path.

**Comment by tsauvajon** [comment]
Additional info:

When I add:
``` js
"plugins": [
        ["module-resolver", {
          "root": ["./src"],
          "alias": {
            "@": "./src"
          }
      }]]
```

to my test env in `.babelrc`, I get errors and all my tests fail:
```
 TypeError: x.match is not a function

      at module.exports (node_modules/module-resolver/index.js:40:8)
```

**Comment by tsauvajon** [comment]
My bad: I installed `module-resolver` instead of `babel-plugin-module-resolver` !

Installing the right npm package solved my issue.
